sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '5'
before_script:
  - npm prune
after_success:
  - npm run build
  - npm run semantic-release
script:
  - npm run test:cov
branches:
  only:
    - master
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
